### ISSUE TITLE
Extractor times out when until parameter is empty string

### ISSUE THREAD

**Issue by ujovlado** [keboola/sklik-extractor#9]
How to reproduce:

```yaml
parameters:
    since: '-60 days'
    until: ''
    bucket: xxx
    username: xxx
    '#password': xxx
    accountId: 'xxx'
    impressionShare: false
```
